spring:
  liquibase:
    change-log: classpath:/db.changelog-master.xml
    enabled: true
  application:
    name: vaxjobostader
  datasource:
    url: jdbc:mariadb://${HOSTNAME:localhost}:3306/${DATABASE_NAME:vaxjo}?allowPublicKeyRetrieval=true
#    url: jdbc:mysql://${HOSTNAME:localhost}:3306/${DATABASE_NAME:vaxjo}?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC

    username: ${DATABASE_USERNAME:vaxjo}
    password: ${DATABASE_PASSWORD}
    hikari:
      max-lifetime: 600000
  jpa:
    hibernate:
      ddl-auto: none
    database: MYSQL
    database-platform: org.hibernate.dialect.MariaDBDialect

server:
  port: ${SERVER_PORT:8080}

log:
  project: ${LOG_LEVEL:INFO}
  spring: ${SPRING_LOG_LEVEL:INFO}

appconfig:
  vbUrl: ${VB_URL:https://bpvx.vaxjo.se/API/Service/SearchServiceHandler.ashx}
  lastDateCron: ${LAST_DATE_CRON}
  databaseUpdateCron: ${DATABASE_UPDATE_CRON}
  slackCron: ${SLACK_CRON}
  vxPrefixLink: ${VX_PREFIX_LINK}
  configFilePath: ${CONFIG_FILE_PATH}

