spring:
  liquibase:
    change-log: classpath:/db.changelog-master.xml
    enabled: true
  application:
    name: vaxjobostader
  datasource:
    url: jdbc:mariadb://${HOSTNAME:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:vaxjo}?allowPublicKeyRetrieval=true
#    url: jdbc:mysql://${HOSTNAME:localhost}:3306/${DATABASE_NAME:vaxjo}?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC

    username: ${DATABASE_USERNAME:vaxjo}
    password: ${DATABASE_PASSWORD}
    hikari:
      max-lifetime: 600000
  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:none}
    database: MYSQL
    database-platform: org.hibernate.dialect.MariaDBDialect

server:
  port: ${SERVER_PORT:8080}

log:
  project: ${LOG_LEVEL:INFO}
  spring: ${SPRING_LOG_LEVEL:INFO}

appconfig:
  vbUrl: ${VB_URL:https://vidingehem-fastighet.momentum.se/Prod/Vidingehem/PmApi/v2/market/objects}
  vbApiKey: ${VB_API_KEY:REDACTED}
  listApiCacheDurationHours: ${LIST_API_CACHE_DURATION_HOURS:24}
  detailApiCallIntervalSeconds: ${DETAIL_API_CALL_INTERVAL_SECONDS:60}
  slackWebhookUrl: ${SLACK_WEBHOOK_URL:https://hooks.slack.com/services/REDACTED/REDACTED/REDACTED}
  lastDateCron: ${LAST_DATE_CRON}
  slackCron: ${SLACK_CRON}
  vxPrefixLink: ${VX_PREFIX_LINK}
  configFilePath: ${CONFIG_FILE_PATH}

