outputChangeLogFile=src/main/resources/db/changelog/create-constants-table.xml
url=jdbc:mysql://localhost:3306/vaxjo?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
username=vaxjo
password=vaxjo